//
//  TrySwift2026App.swift
//
//  This file is automatically generated by SlideGen
//

import SwiftUI
import SlideKit

@main
struct TrySwift2026App: App {

    /// Edit slide configurations in SlideConfiguration.swift
    private static let configuration = SlideConfiguration()

    /// A presentation content view.
    /// Edit the view here if you'd like to set environments, overlay views or background views.
    var presentationContentView: some View {
        SlideRouterView(slideIndexController: Self.configuration.slideIndexController)
            .background(.white)
            .foregroundColor(.black)
    }

    var body: some Scene {
        WindowGroup {
            PresentationView(slideSize: Self.configuration.size) {
                presentationContentView
            }
        }
        .setupAsPresentationWindow(Self.configuration.slideIndexController) {
            NSWorkspace.shared.open(URL(string: "TrySwift2026://editor")!)
        }
        .addPDFExportCommands(for: presentationContentView, with: Self.configuration.slideIndexController, size: Self.configuration.size)
        .commands {
            CommandGroup(after: .importExport) {
                Button("Export All Slides as PDF...") {
                    PDFExporter(slideSize: Self.configuration.size).exportAll()
                }
                Button("Copy All Scripts to Clipboard") {
                    let scripts = sequence(first: 0, next: { $0 + 1 })
                        .prefix(while: { SlideState(rawValue: $0) != nil })
                        .compactMap { SlideState(rawValue: $0) }
                        .map { slide(for: $0).script }
                        .filter { !$0.isEmpty }
                        .joined(separator: "\n\n")
                    NSPasteboard.general.clearContents()
                    NSPasteboard.general.setString(scripts, forType: .string)
                }
            }
        }

        WindowGroup {
            macOSPresenterView(
                slideSize: Self.configuration.size,
                slideIndexController: Self.configuration.slideIndexController
            ) {
                presentationContentView
            }
        }
        .setupAsPresenterWindow()
    }
}

//
//  macOSPresenterView.swift
//
//
//  Created by Junnosuke Matsumoto on 2022/08/31.
//

#if os(macOS)
import Combine
import Foundation
import SwiftUI

public struct macOSPresenterView<Content>: View where Content: View {

    private let slideSize: CGSize
    private let content: () -> Content

    @State
    private var startDate = Date()

    @ObservedObject
    private var slideIndexController: SlideIndexController

    public init(
        slideSize: CGSize,
        slideIndexController: SlideIndexController,
        content: @escaping () -> Content
    ) {
        self.slideSize = slideSize
        self.slideIndexController = slideIndexController
        self.content = content
    }

    public var body: some View {
        VStack {
            HStack {
                SlideScreen(slideSize: slideSize) {
                    content()
                }
                .clipped()
            }
            VStack(alignment: .leading) {
                scriptView
                stopwatch
            }
            .padding(.horizontal)
            .padding(.bottom)
            .frame(minHeight: 100)
        }
        .background(.black)
        .background(KeyWindowForwarder())
    }

    private var scriptView: some View {
        ScrollView {
            Text(slideIndexController.currentSlide.script)
                .foregroundColor(.white)
                .multilineTextAlignment(.leading)
                .lineLimit(nil)
                .frame(maxWidth: .infinity, alignment: .leading)
                .font(.system(size: 60, weight: .medium))
        }
        .frame(minHeight: 100)
    }

    private var stopwatch: some View {
        HStack {
            Button {
                startDate = Date()
            } label: {
                Image(systemName: "arrow.counterclockwise.circle.fill")
                    .resizable()
                    .scaledToFit()
                    .frame(width: 20, height: 20)
            }
            .buttonStyle(.plain)
            Text(startDate, style: .timer)
                .font(.title)
                .fontWeight(.heavy)
        }
        .foregroundColor(.white)
    }
}

private struct KeyWindowForwarder: NSViewRepresentable {
    func makeNSView(context: Context) -> NSView {
        KeyWindowForwardingNSView()
    }

    func updateNSView(_ nsView: NSView, context: Context) {}
}

private final class KeyWindowForwardingNSView: NSView {
    private var observation: (any NSObjectProtocol)?

    override func viewDidMoveToWindow() {
        super.viewDidMoveToWindow()
        if let observation {
            NotificationCenter.default.removeObserver(observation)
        }
        observation = nil
        guard let window else { return }
        observation = NotificationCenter.default.addObserver(
            forName: NSWindow.didBecomeKeyNotification,
            object: window,
            queue: .main
        ) { [weak window] _ in
            guard let window else { return }
            let presentationWindow = NSApp.windows.first { $0 !== window && $0.isVisible && !$0.isMiniaturized }
            presentationWindow?.makeKey()
        }
    }

    deinit {
        if let observation {
            NotificationCenter.default.removeObserver(observation)
        }
    }
}

class Stopwatch: ObservableObject {

    @Published var startDate = Date()
    @Published var elapsedTime: TimeInterval = .zero

    private var cancellable: AnyCancellable?

    init() {
        cancellable = Timer.publish(every: 1, on: .main, in: .default)
            .autoconnect()
            .sink(receiveValue: { [weak self] _ in
                guard let self else { return }
                self.elapsedTime = Date().timeIntervalSince(self.startDate)
            })
    }
}
#endif
